services:
    onfly_travel_app:
        build:
            args:
                user: onfly
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - onfly_travel_network

    onfly_travel_nginx:
        image: nginx:alpine
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/

        networks:
            - onfly_travel_network

    onfly_travel_db:
        image: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        networks:
            - onfly_travel_network


networks:
    onfly_travel_network:
        driver: bridge
